// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkw4rYIHjgA7Cv0ie6ImG2esjwa_qZsXo',
    appId: '1:436529598464:web:3ad74a84083d760e4008e5',
    messagingSenderId: '436529598464',
    projectId: 'subzero-75c8a',
    authDomain: 'subzero-75c8a.firebaseapp.com',
    storageBucket: 'subzero-75c8a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjuj501zeuwD5iKthYLMCJV756hco7c1E',
    appId: '1:436529598464:android:4cfbfcbae96646c04008e5',
    messagingSenderId: '436529598464',
    projectId: 'subzero-75c8a',
    storageBucket: 'subzero-75c8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Vj9Pp1JDmuI6DtnqUtMIeWtZofegGOg',
    appId: '1:436529598464:ios:cde5c212d220fadc4008e5',
    messagingSenderId: '436529598464',
    projectId: 'subzero-75c8a',
    storageBucket: 'subzero-75c8a.firebasestorage.app',
    iosBundleId: 'com.example.subzeroMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Vj9Pp1JDmuI6DtnqUtMIeWtZofegGOg',
    appId: '1:436529598464:ios:cde5c212d220fadc4008e5',
    messagingSenderId: '436529598464',
    projectId: 'subzero-75c8a',
    storageBucket: 'subzero-75c8a.firebasestorage.app',
    iosBundleId: 'com.example.subzeroMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkw4rYIHjgA7Cv0ie6ImG2esjwa_qZsXo',
    appId: '1:436529598464:web:52606fb61027f73d4008e5',
    messagingSenderId: '436529598464',
    projectId: 'subzero-75c8a',
    authDomain: 'subzero-75c8a.firebaseapp.com',
    storageBucket: 'subzero-75c8a.firebasestorage.app',
  );
}
