// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWMBWW0oLXFTXl1MKWc943Kj7u1ky7joY',
    appId: '1:212836452658:web:632fa5ab1c972a51376f2b',
    messagingSenderId: '212836452658',
    projectId: 'code-83c74',
    authDomain: 'code-83c74.firebaseapp.com',
    databaseURL: 'https://code-83c74.firebaseio.com',
    storageBucket: 'code-83c74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvWhb_Ny0tWR9KkHvperK5nVxMwDMhokg',
    appId: '1:212836452658:android:5e3bf1f4d80a286d376f2b',
    messagingSenderId: '212836452658',
    projectId: 'code-83c74',
    databaseURL: 'https://code-83c74.firebaseio.com',
    storageBucket: 'code-83c74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdZl355ODmJxUyNzLlRTcRy5Iz1vxI5zc',
    appId: '1:212836452658:ios:4c6c2f1afee2d306376f2b',
    messagingSenderId: '212836452658',
    projectId: 'code-83c74',
    databaseURL: 'https://code-83c74.firebaseio.com',
    storageBucket: 'code-83c74.firebasestorage.app',
    iosBundleId: 'com.example.subzeroMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdZl355ODmJxUyNzLlRTcRy5Iz1vxI5zc',
    appId: '1:212836452658:ios:4c6c2f1afee2d306376f2b',
    messagingSenderId: '212836452658',
    projectId: 'code-83c74',
    databaseURL: 'https://code-83c74.firebaseio.com',
    storageBucket: 'code-83c74.firebasestorage.app',
    iosBundleId: 'com.example.subzeroMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWMBWW0oLXFTXl1MKWc943Kj7u1ky7joY',
    appId: '1:212836452658:web:70b4a90d266f92e1376f2b',
    messagingSenderId: '212836452658',
    projectId: 'code-83c74',
    authDomain: 'code-83c74.firebaseapp.com',
    databaseURL: 'https://code-83c74.firebaseio.com',
    storageBucket: 'code-83c74.firebasestorage.app',
  );

}